#!/usr/bin/env python3
"""Turn agent-written proposals.json into a Feature Proposals issue body.

The agent's only job is to produce JSON. This script validates it and renders
the issue, so a bad model response fails here with a readable error instead of
opening a malformed issue.

Usage:
    python scripts/proposals_to_issue.py \
        --proposals proposals.json \
        --body-out issue_body.md \
        --title-out issue_title.txt
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from proposal_io import (
    ProposalError,
    embed_payload,
    load_payload,
    validate_payload,
)

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SCHEMA = PROJECT_ROOT / ".github" / "agent-prompts" / "proposals.schema.json"

SIZE_HINT = {
    "small": "a focused change, under an hour of work",
    "medium": "a normal feature, a few files",
    "large": "big enough that it may need slicing",
}


def render_title(payload: dict[str, Any]) -> str:
    meeting = payload.get("meeting_title") or Path(payload["source_transcript"]).stem
    count = len(payload["proposals"])
    noun = "proposal" if count == 1 else "proposals"
    return f"Feature proposals: {meeting} ({count} {noun})"


def render_body(payload: dict[str, Any], run_url: str | None = None) -> str:
    proposals = payload["proposals"]
    lines: list[str] = []

    lines += [
        f"Parsed from [`{payload['source_transcript']}`]"
        f"(../blob/HEAD/{payload['source_transcript']}) by the transcript agent.",
        "",
    ]

    if payload.get("meeting_date"):
        lines += [f"Meeting date: {payload['meeting_date']}", ""]

    if not proposals:
        lines += [
            "The agent found no actionable work in this transcript.",
            "",
            _render_excluded(payload),
            "",
            embed_payload(payload),
        ]
        return "\n".join(line for line in lines if line is not None) + "\n"

    lines += [
        "## How to approve",
        "",
        "Comment on this issue with one of:",
        "",
        "| comment | effect |",
        "| --- | --- |",
        "| `/approve` | create an issue for every proposal below |",
        "| `/approve 1,3` | create issues for proposals 1 and 3 only |",
        "| `/approve 2-4` | create issues for proposals 2 through 4 |",
        "",
        "Each approved proposal becomes its own issue, assigned to the Copilot",
        "cloud agent, which opens a draft pull request. Only users with write",
        "access can approve. The checkboxes below are for your own notes; the",
        "comment is what the workflow acts on.",
        "",
        "---",
        "",
        f"## Proposals ({len(proposals)})",
        "",
    ]

    for index, proposal in enumerate(proposals, start=1):
        lines += _render_proposal(index, proposal)

    excluded = _render_excluded(payload)
    if excluded:
        lines += ["---", "", excluded, ""]

    if run_url:
        lines += [f"<sub>Generated by [this workflow run]({run_url}).</sub>", ""]

    lines += [embed_payload(payload)]
    return "\n".join(lines) + "\n"


def _render_proposal(index: int, proposal: dict[str, Any]) -> list[str]:
    size = proposal["size"]
    labels = proposal.get("labels") or []

    lines = [
        f"### {index}. {proposal['title']}",
        "",
        f"- [ ] **Approve proposal {index}**",
        "",
        f"**Size:** `{size}` ({SIZE_HINT.get(size, '')})  ",
        f"**Labels:** {', '.join(f'`{label}`' for label in labels) if labels else '_none_'}",
        "",
        "**Problem**",
        "",
        proposal["problem"],
        "",
        "**Acceptance criteria**",
        "",
    ]

    lines += [f"- {criterion}" for criterion in proposal["acceptance_criteria"]]
    lines.append("")

    files = proposal.get("suggested_files") or []
    if files:
        lines += ["**Likely files**", ""]
        lines += [f"- `{path}`" for path in files]
        lines.append("")

    if proposal.get("notes"):
        lines += ["**Notes**", "", proposal["notes"], ""]

    if proposal.get("transcript_evidence"):
        lines += ["**From the transcript**", "", f"> {proposal['transcript_evidence']}", ""]

    return lines


def _render_excluded(payload: dict[str, Any]) -> str:
    excluded = payload.get("excluded") or []
    if not excluded:
        return ""

    lines = [
        "## Discussed but not proposed",
        "",
        "| topic | why it was left out |",
        "| --- | --- |",
    ]
    for item in excluded:
        topic = item["topic"].replace("|", "\\|")
        reason = item["reason"].replace("|", "\\|")
        lines.append(f"| {topic} | {reason} |")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--proposals", type=Path, default=Path("proposals.json"))
    parser.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA)
    parser.add_argument("--body-out", type=Path, default=Path("issue_body.md"))
    parser.add_argument("--title-out", type=Path, default=Path("issue_title.txt"))
    parser.add_argument("--run-url", default=None, help="Link back to the workflow run")
    parser.add_argument(
        "--source-transcript",
        default=None,
        help="Override source_transcript when the agent guessed the path wrong",
    )
    args = parser.parse_args()

    try:
        payload = load_payload(args.proposals)
        if args.source_transcript:
            payload["source_transcript"] = args.source_transcript
        payload = validate_payload(payload, args.schema)
    except ProposalError as error:
        print(f"::error::{error}", file=sys.stderr)
        return 1

    title = render_title(payload)
    body = render_body(payload, run_url=args.run_url)

    args.body_out.write_text(body, encoding="utf-8")
    args.title_out.write_text(title, encoding="utf-8")

    print(f"title      : {title}")
    print(f"proposals  : {len(payload['proposals'])}")
    print(f"excluded   : {len(payload.get('excluded', []))}")
    print(f"body       : {args.body_out} ({len(body)} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
